language: node_js
node_js: 8

services:
  - redis-server

cache:
  directories:
    - node_modules

env:
  global:
    - CACHE_TIME=300000
    - REDISCLOUD_URL=redis://127.0.0.1

script:
  - snyk test
  - npm test