language: node_js
node_js: 9
sudo: false

services:
  - redis-server

cache:
  directories:
    - node_modules

env:
  global:
    - CACHE_TIME=300000
    - PORT=5000
    - REDISCLOUD_URL=redis://127.0.0.1
    - ORIGIN_WHITELIST=localhost,127.0.0.1
    - LOG_LEVEL=emerg
    - TARGET_WHITELIST=127.0.0.1

deploy:
  provider: heroku
  api_key:
    secure: ov42lnlMN0MoI14um9F8ZbbL2+dWnQeNuIucyQ4QmxvJ5l4I+com0SNucA2bWL1odacRNhF3v97XhqGh2qnoHi9bC4dTatZQqWa/DZjnsXLv8zIYG1NhMz4Wtp15AMnLVKgsYfBRZTqogp/PR7V2s3dwEtz0hlkybB4ngcekAjnbeI7pSFgSCVBlhgn4GGxP7bw1zMHU5ZlacOMYxsS8Vui3zGMkmo7xubJ/hpnmETBPRDB+blGAcWHWyVQK/47FL0IJ4dq7ytMTjZehM3LOUfJ9zdPk5Wn/toha24aSYdDWJOMCFdfvgPDHxhE5OE3liIuQ5jJcaKH+d8UpzFLntF57YE5cT4H6b0kPJZ7mMq9fb/Wb97gdF+wv/hJfHZ6Jkx34LdOGZpXgegWb93JJzKWaYfEAkRi/d4/8QRPsTWOuNjYzNdoltzt1oiYu06oUJ2HE26PlmeAXt4lsN1Ir6B6iXAU3VEbT+4ahAtDKAnihbPWFcgm/48ZSdVhLDRiJZWOX4RgZXcnV2+gi9T7bRmynWtKyJohjmNX9ugRniL1Hbmw9fONs/hBIEInI689eWXAcOT5QPck2xpQzzB+yZWax6lOrmDIKqUtehDNGHrqrCyO4jZOKdS5SLO6s+5I5L0NXoLDkVjcMlQyXkF5ES6kssbjazm0qPyhf36Ev/Xk=
  app: alore-cors-proxy
  on:
    tags: true
