language: node_js
node_js: 8
sudo: false

services:
  - redis-server

cache:
  directories:
    - node_modules

env:
  global:
    - CACHE_TIME=300000
    - PORT=5000
    - REDISCLOUD_URL=redis://127.0.0.1
    - ORIGIN_WHITELIST=localhost,127.0.0.1
    - LOG_LEVEL=emerg

script:
  - snyk test
  - npm test