language: node_js
sudo: false
node_js:
  - 9
  - 8
  - 7
services: redis-server
cache:
  directories:
    - node_modules
after_success: cat ./coverage/lcov.info | coveralls
before_cache: rm -rf ./node_modules/.cache
before_script: greenkeeper-lockfile-update
after_script:
  - if [ $GH_TOKEN ]; then greenkeeper-lockfile-upload; fi;
  - if [ $SNYK_TOKEN ]; then snyk monitor; fi;
script:
  - snyk test --dev
  - npm test
env:
  global:
    - CACHE_TIME=300000
    - PORT=5000
    - REDISCLOUD_URL=redis://127.0.0.1
    - ORIGIN_WHITELIST=localhost,127.0.0.1
    - LOG_LEVEL=error
    - TARGET_WHITELIST=127.0.0.1
    - secure: TazUcYlNOoZTM94l/qf2eYGHphz1mdYDXqga8wYrpPtre9ZRJ88BHTjxICwDpaz9PC8W/Uh0rrnXZhukdk+Y2yXanN+L9G1SBuMmLO80IuFwHGOJGpZnk3TnqCXAtJgKwlacevORydF7xIFstKlwSu5QUPKyqPkuhExDbyybEGd4Z5rfNIHakYBKBNX2lXvhXViU3/t6kzNxvdxX4IC+R6m4p1wOdM0CgXV//NnCPjGAsvrmy+9jvgxIIlRY/bez5qTE6YlAdLh7F4E6CFFRIdD6a5Gz8EZhxtpj4kOoD9Qh1LsCPerht7jtr/lEkcRrh1avIB6Nt4egnWyXKHMyMYW8Wo4z/TY8odXIhWPT/BnNOYT0kx71a/q8uz7WYpa7URuog0tteRAyogChnhOL3qzEMKhsWNbqKcKTMXmEshXn04qIgrEzrmKchylqkYDkjwvbfPUhE0Nbf8CpEKlhnpiG0wFCVPnKakk9CpSD52dNizWrnUYzf/dxTni9NVueswmlEBdcjpp8BUh3/6SpmFJtX3rdDCmR6JgDMlBJw/VrxOzUhmIqrliMLXu6PjP0UFGwIe0D2xb5ZXloRSy7XfGsfNytaNOVfhyD7D3rPRD05wzmxKweSQOV3pNZJPt/saUc7keNVLqn3U6CQ5Ga9V39nol/xSORQE3fhWu8Bm8=
    - secure: x7ziPq8jOVZrd5iMgF/N/ll7pHBRIwA5FskrtWvG4vRd6tA8DFQgZXY8ot9Fiard660SI2D1OqX7PoJL8lvbhLrRJsfFn5sgAZlzXqNGBGiLj4N67UCD4RkdwSPcGYxWPFe6eTNdpGnijKGKY9NGmxh/uPDCk0/PbLqYzGtI3K9j6iJ2cPSAzvXglgB15gquI94ordW6Yg1kHeevGte0KQGQYPvs0He+rxhneedndBnEMGhBNOY1SdVswo4qOTzjhzO1CURkgNHD1V4yNa0HYSXQWx7CbmbFD1nB5aVRmaThIEZX+nTOeiqruaS3WJ0GiSYCemt2A1gIbfK+KTt4gehnqcwAYaCDR6AEwEfnasNfFAxFm9MIKtum2s0pUwHvN27IQGrtZG/eVdzG/e9tUTy1/CFnX5WZHb8Ccsk4P9taqIKV00uC7gKLJZQAUGdqPCNvP/KN7kRlFKuvj3MHMH7g2quZ5ciL8Zt/OIAByQGRtWXZ/ltta3xU7a6SDcx7iSbbpphFrcUFXxU10GriVeOp2THCyBOk0Dj7rAZ+x9jBl1xS2U4flx/F2o4JzSYmU5YxlHZgmOkJsquVT55GuT+yv2Dyk/Cp5N0aeanSO8c2i+b7COIMeFHMOac0i8gFSYq4uWqM3aSB8j7YR56EpbrpQvlUUIg8xxarrZKiRC8=
